### ISSUE TITLE
Microsoft.Compute/virtualMachines - Encryption settings for subs not having feature enabled

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1273]
## Description

VM module has the `encryptionAtHost` setting as `True` by default. However, in subscriptions where this feature is not enabled, the VM deployment fails.

This issue should end up with a decision and actions taken so we are sure that the consumer knows what to do when this setting is set to True. It should also end with a decision if we should set to true by default, relying on a discussion regarding what "secure by default" means.

**Comment by MariusStorhaug** [comment]
Could also be as easy as guiding the consumer to run the following:

azure-pipeline.yml
```yaml
- stage: Prep
  displayName: Prepare subscription
  jobs:
  - job: PrepSub
    displayName: Prepare subscription
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: 'InlineScript'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
        Inline: |
          . .\Scripts\EnableResourceProviders\Enable-ResourceProviders.ps1 -Verbose
```

The `Enable-ResourceProviders.ps1` script
```pwsh
[CmdletBinding()]
param ()

$ResourceProviders = Get-Content -Path $PSScriptRoot\ResourceProviders.json -Raw | ConvertFrom-Json

foreach ($ResourceProvider in $ResourceProviders) {
    Register-AzResourceProvider -ProviderNamespace $ResourceProvider.name
    foreach ($feature in $ResourceProvider.features) {
        Register-AzProviderFeature -ProviderNamespace $ResourceProvider.name -FeatureName $feature
    }
}
```

The `ResourceProviders.json` file:
```json
[
    {
        "name": "Microsoft.Compute",
        "features": [
            "EncryptionAtHost"
        ]
    }
]
```
