### ISSUE TITLE
[Feature Request]: Auto-Assign Features & Bugs

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1454]
### Description

Implement a pipeline that automatically assigns Bugs & Features to projects. Example code:

```yaml
# Add new issues to the corrrect project
name: Assign Issues to Projects

on:
# Triggers the workflow on push or pull request events but only for the main branch
issues:
types:
- opened

# Allows you to run this workflow manually from the Actions tab
workflow_dispatch:

env: GITHUB_TOKEN: ${{ github.token }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-to-project:
    name: Add Issues to Projects
    runs-on: ubuntu-latest
    steps:
      - name: Add Bug to Bug Board
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: contains(github.event.issue.labels.*.name, 'bug')
          with:
            project: https://github.com/users/mblant/board-test/projects/2
      - name: Add Issues to Backlog Board
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: contains(github.event.issue.labels.*.name, 'needs triage')
          with:
              project: https://github.com/users/mblant/board-test/projects/1
```
