### ISSUE TITLE
Workflow trigger path filters are incorrect

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#518]
The workflow path filters do not yet account for the new child-resource structure. To be more precise, the `exclude` filter only accounts for the top-level readme and not the ones on lower levels. 

For example
```yaml
  push:
    branches:
      - main
    paths:
      - '.github/actions/templates/**'
      - '.github/workflows/ms.network.virtualwans.yml'
      - 'arm/Microsoft.Network/virtualWans/**'
      - '!arm/Microsoft.Network/virtualWans/readme.md'
```
