### ISSUE TITLE
The AzureDevOps Platform Pipeline to set the readme is flawed

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#960]
The pipeline (ResourceModules/.azuredevops/platformPipelines/platform.updateReadMe.yml) has 3 issues that must be fixed

1. The pool reference should be
    ```yaml
          ${{ if ne(variables.vmImage, '') }}:
            vmImage: ${{ variables.vmImage }}
          ${{ if ne(variables.poolName, '') }}:
            name: ${{ variables.poolName }}
   ```

2. The input object used in the pipeline did not work at a customer
```Powershell
         $functionInput = @{
              ModulesPath    = Join-Path '$(System.DefaultWorkingDirectory)' 'arm'
              FilePath       = Join-Path '$(System.DefaultWorkingDirectory)' 'arm/README.md'
              Organization   = ('$(Build.Repository.Name)').split('/')[0] # HERE: returned the repo name
              RepositoryName = ('$(Build.Repository.Name)').split('/')[1] # HERE: returned empty
              ColumnsInOrder = @('Name', 'ProviderNamespace','ResourceType')
            }
```

3. The pipeline uses the script `Set-GitHubReadMeModuleTable @functionInput -Verbose` which is not Azure DevOps ready. The script should be updated to take GitHub vs AzureDevOps as an input parameter, should be renamed and also updated accordingly (e.g. the generated module links are all GitHub links)
